# Generated by Django 3.1.1 on 2020-09-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='Item',
            field=models.TextField(default=10, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Name',
            field=models.TextField(default=10, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Phonenumber',
            field=models.TextField(default=10, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Quantity',
            field=models.TextField(default=10, max_length=35),
            preserve_default=False,
        ),
    ]
